# Generated by Django 5.2.6 on 2025-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_images/'),
        ),
    ]
