# Generated by Django 5.2.6 on 2025-10-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_booking_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='image',
        ),
        migrations.AddField(
            model_name='booking',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
